#!/usr/bin/env python3
"""
AO-friendly autopilot runner for MoneyPrinterTurbo.

This script does not try to edit source code autonomously. It runs safe,
deterministic maintenance steps, evaluates the current system state, and
applies bounded actions to keep the pipeline moving:

1) bootstrap DB schema
2) apply known safe fix recipes
3) syntax-check critical files
4) run auto-agent audit and parse machine-readable findings
5) trigger upload retries for ready videos when throughput is blocked
6) optionally capture AO status/start output for the cycle log
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List


ROOT = Path(__file__).resolve().parents[1]
RUNS_DIR = ROOT / "storage" / "ao-runs"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _run(cmd: List[str], cwd: Path | None = None, timeout: int = 600) -> Dict[str, Any]:
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd or ROOT),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return {
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
        }
    except Exception as e:
        return {
            "ok": False,
            "returncode": -1,
            "stdout": "",
            "stderr": str(e),
        }


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _bootstrap_db() -> Dict[str, Any]:
    try:
        from app.db.engine import init_db

        init_db()
        return {"ok": True}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def _parse_json_stdout(result: Dict[str, Any]) -> Dict[str, Any]:
    if not result.get("stdout"):
        return {}
    try:
        return json.loads(result["stdout"])
    except json.JSONDecodeError:
        return {}


def _critical_compile_targets() -> List[str]:
    return [
        "app/services/youtube_service.py",
        "app/worker/tasks.py",
        "app/services/task.py",
        "scripts/auto_agent.py",
        "scripts/auto_fix_recipes.py",
        "scripts/auto_upload_candidates.py",
        "scripts/backfill_revenue_tags.py",
        "scripts/ao_auto_orchestrator.py",
    ]


def _read_file(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return ""


def _affiliate_placeholder_count() -> int:
    patterns = [
        r"\[YOUR_[A-Z_]+\]",
        r"\[AFFILIATE_[A-Z_]+\]",
        r"\[LANDING_[A-Z_]+\]",
    ]
    targets = [
        ROOT / "app" / "services" / "monetization.py",
        ROOT / "app" / "services" / "revenue_optimization.py",
        ROOT / "app" / "services" / "revenue_orchestrator.py",
    ]
    total = 0
    for target in targets:
        content = _read_file(target)
        for pattern in patterns:
            total += len(re.findall(pattern, content))
    return total


def _revenue_dashboard_is_simulated() -> bool:
    content = _read_file(ROOT / "dashboard" / "js" / "pages" / "revenue.js")
    markers = [
        "Dummy logic to simulate revenue",
        "Math.random()",
        "Projected Monthly",
    ]
    return any(marker in content for marker in markers)


def _youtube_safe_metadata_enabled() -> bool:
    content = _read_file(ROOT / "app" / "services" / "youtube_service.py")
    return "Generated by automation." in content and "invalidDescription" in content


def _revenue_focus_snapshot(audit: Dict[str, Any]) -> Dict[str, Any]:
    metrics = audit.get("metrics", {}) or {}
    return {
        "uploads_total": int(metrics.get("uploads_total", 0) or 0),
        "uploads_recent": int(metrics.get("uploads_recent", 0) or 0),
        "jobs_completed": int(metrics.get("jobs_completed", 0) or 0),
        "affiliate_placeholder_count": _affiliate_placeholder_count(),
        "dashboard_simulated": _revenue_dashboard_is_simulated(),
        "youtube_safe_metadata_enabled": _youtube_safe_metadata_enabled(),
    }


def _should_trigger_uploads(audit: Dict[str, Any], mode: str) -> bool:
    metrics = audit.get("metrics", {}) or {}
    findings = audit.get("top_findings", []) or []
    uploads_recent = int(metrics.get("uploads_recent", 0) or 0)
    has_upload_block = any("No recent upload throughput" in item for item in findings)
    if mode == "revenue-first" and int(metrics.get("jobs_completed", 0) or 0) > 0:
        return uploads_recent == 0 or has_upload_block
    return uploads_recent == 0 or has_upload_block


def _recommended_actions(audit: Dict[str, Any], mode: str) -> List[str]:
    metrics = audit.get("metrics", {}) or {}
    actions: List[str] = []

    if mode == "revenue-first":
        revenue_state = _revenue_focus_snapshot(audit)
        if revenue_state["uploads_recent"] == 0:
            actions.append("trigger_upload_candidates")
        if revenue_state["affiliate_placeholder_count"] > 0:
            actions.append("replace_affiliate_placeholders")
        if revenue_state["dashboard_simulated"]:
            actions.append("wire_real_revenue_dashboard")
        if revenue_state["uploads_total"] == 0:
            actions.append("connect_real_revenue_tracking")
        if not revenue_state["youtube_safe_metadata_enabled"]:
            actions.append("restore_safe_upload_metadata_fallback")
    else:
        if int(metrics.get("uploads_recent", 0) or 0) == 0:
            actions.append("trigger_upload_candidates")
        if int(metrics.get("jobs_pending", 0) or 0) > 0:
            actions.append("inspect_queue_backlog")
        if int(metrics.get("jobs_failed", 0) or 0) > 0:
            actions.append("review_top_failures")
    if not actions:
        actions.append("monitor_only")
    return actions


def _ao_status() -> Dict[str, Any]:
    return _run(["ao.cmd", "status"], timeout=120)


def _ao_start(project: str, no_dashboard: bool) -> Dict[str, Any]:
    cmd = ["ao.cmd", "start", project]
    if no_dashboard:
        cmd.append("--no-dashboard")
    return _run(cmd, timeout=180)


def run_cycle(
    hours: int,
    max_uploads: int,
    mode: str,
    with_ao: bool,
    ao_project: str,
    ao_start_if_needed: bool,
    ao_no_dashboard: bool,
) -> Dict[str, Any]:
    now_utc = dt.datetime.now(dt.UTC)
    stamp = now_utc.strftime("%Y%m%d-%H%M%S")
    cycle_dir = RUNS_DIR / stamp
    cycle_dir.mkdir(parents=True, exist_ok=True)

    summary: Dict[str, Any] = {
        "cycle_id": stamp,
        "started_at_utc": now_utc.isoformat(),
        "mode": mode,
    }

    bootstrap = _bootstrap_db()
    summary["bootstrap_db"] = bootstrap

    fixes = _run([sys.executable, "scripts/auto_fix_recipes.py"], timeout=180)
    _write_text(cycle_dir / "fixes.stdout.txt", fixes.get("stdout", ""))
    _write_text(cycle_dir / "fixes.stderr.txt", fixes.get("stderr", ""))
    summary["fixes"] = {
        "ok": fixes["ok"],
        "returncode": fixes["returncode"],
        "json": _parse_json_stdout(fixes),
    }

    compile_check = _run([sys.executable, "-m", "py_compile", *_critical_compile_targets()], timeout=180)
    _write_text(cycle_dir / "py_compile.stdout.txt", compile_check.get("stdout", ""))
    _write_text(cycle_dir / "py_compile.stderr.txt", compile_check.get("stderr", ""))
    summary["compile_check"] = {
        "ok": compile_check["ok"],
        "returncode": compile_check["returncode"],
    }

    audit_md = cycle_dir / "report.md"
    audit_result = _run(
        [sys.executable, "scripts/auto_agent.py", "--hours", str(hours), "--output", str(audit_md)],
        timeout=180,
    )
    _write_text(cycle_dir / "audit.stdout.txt", audit_result.get("stdout", ""))
    _write_text(cycle_dir / "audit.stderr.txt", audit_result.get("stderr", ""))
    audit_json = _parse_json_stdout(audit_result)
    summary["audit"] = audit_json
    summary["recommended_actions"] = _recommended_actions(audit_json, mode=mode)
    if mode == "revenue-first":
        backfill = _run([sys.executable, "scripts/backfill_revenue_tags.py"], timeout=180)
        _write_text(cycle_dir / "backfill.stdout.txt", backfill.get("stdout", ""))
        _write_text(cycle_dir / "backfill.stderr.txt", backfill.get("stderr", ""))
        summary["backfill_revenue_tags"] = {
            "ok": backfill["ok"],
            "returncode": backfill["returncode"],
            "json": _parse_json_stdout(backfill),
        }
        summary["revenue_focus"] = _revenue_focus_snapshot(audit_json)

    upload_result: Dict[str, Any] = {"skipped": True}
    if _should_trigger_uploads(audit_json, mode=mode):
        upload_cmd = [
            sys.executable,
            "scripts/auto_upload_candidates.py",
            "--max",
            str(max_uploads),
        ]
        if mode == "revenue-first":
            upload_cmd.append("--prefer-completed-only")
            upload_cmd.extend(["--require-money-signal", "--min-score", "80"])
        upload_proc = _run(
            upload_cmd,
            timeout=300,
        )
        _write_text(cycle_dir / "uploads.stdout.txt", upload_proc.get("stdout", ""))
        _write_text(cycle_dir / "uploads.stderr.txt", upload_proc.get("stderr", ""))
        upload_result = {
            "skipped": False,
            "ok": upload_proc["ok"],
            "returncode": upload_proc["returncode"],
            "json": _parse_json_stdout(upload_proc),
        }
    summary["upload_retry"] = upload_result

    if with_ao:
        ao_status = _ao_status()
        _write_text(cycle_dir / "ao_status.stdout.txt", ao_status.get("stdout", ""))
        _write_text(cycle_dir / "ao_status.stderr.txt", ao_status.get("stderr", ""))
        summary["ao_status"] = {
            "ok": ao_status["ok"],
            "returncode": ao_status["returncode"],
        }
        if ao_start_if_needed and not ao_status["ok"]:
            ao_start = _ao_start(project=ao_project, no_dashboard=ao_no_dashboard)
            _write_text(cycle_dir / "ao_start.stdout.txt", ao_start.get("stdout", ""))
            _write_text(cycle_dir / "ao_start.stderr.txt", ao_start.get("stderr", ""))
            summary["ao_start"] = {
                "ok": ao_start["ok"],
                "returncode": ao_start["returncode"],
            }

    summary["completed_at_utc"] = dt.datetime.now(dt.UTC).isoformat()
    summary["cycle_dir"] = str(cycle_dir)
    _write_json(cycle_dir / "summary.json", summary)
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Run AO-friendly autopilot maintenance cycle.")
    parser.add_argument("--hours", type=int, default=48, help="Audit lookback window in hours")
    parser.add_argument("--max-uploads", type=int, default=2, help="Max upload retries per cycle")
    parser.add_argument(
        "--mode",
        choices=["default", "revenue-first"],
        default="default",
        help="Operating mode for action prioritization",
    )
    parser.add_argument("--with-ao", action="store_true", help="Capture AO status and optional start")
    parser.add_argument("--ao-project", default="MoneyPrinterTurbo", help="AO project/session name")
    parser.add_argument("--ao-start-if-needed", action="store_true", help="Start AO when status fails")
    parser.add_argument("--ao-no-dashboard", action="store_true", help="Pass --no-dashboard to ao.cmd start")
    args = parser.parse_args()

    summary = run_cycle(
        hours=args.hours,
        max_uploads=args.max_uploads,
        mode=args.mode,
        with_ao=args.with_ao,
        ao_project=args.ao_project,
        ao_start_if_needed=args.ao_start_if_needed,
        ao_no_dashboard=args.ao_no_dashboard,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
